CREATE DATABASE DEBTNAG;

CREATE TABLE DEBTNAG.USER (
       ID INT NOT NULL AUTO_INCREMENT
     , NICK VARCHAR(100) NOT NULL
     , EMAIL VARCHAR(255) NOT NULL
     , PWD VARCHAR(500)
     , NAGINTERVAL INT
     , PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE DEBTNAG.CONTACT (
       ID INT NOT NULL AUTO_INCREMENT
     , NICK VARCHAR(100) NOT NULL
     , EMAIL VARCHAR(255) NOT NULL
     , NAG INT
     , FK_USER_ID INT NOT NULL
     , PRIMARY KEY (ID)
     , INDEX (FK_USER_ID)
     , CONSTRAINT FK_CONTACT_1 FOREIGN KEY (FK_USER_ID)
                  REFERENCES DEBTNAG.USER (ID) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE DEBTNAG.DEBT (
       ID INT NOT NULL AUTO_INCREMENT
     , DATE DATETIME NOT NULL
     , DESCRIPTION VARCHAR(255)
     , SUM DOUBLE NOT NULL
     , FK_USER_ID INT NOT NULL
     , FK_CONTACT_ID INT NOT NULL
     , PRIMARY KEY (ID)
     , INDEX (FK_USER_ID)
     , CONSTRAINT FK_DEBT_1 FOREIGN KEY (FK_USER_ID)
                  REFERENCES DEBTNAG.USER (ID)
     , INDEX (FK_CONTACT_ID)
     , CONSTRAINT FK_DEBT_2 FOREIGN KEY (FK_CONTACT_ID)
                  REFERENCES DEBTNAG.CONTACT (ID) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

