CREATE TABLE USER (
       ID INT NOT NULL
     , NICK VARCHAR(100) NOT NULL
     , EMAIL VARCHAR(255) NOT NULL
     , PWD VARCHAR(500)
     , NAGINTERVAL INT
     , CREATED DATETIME
     , LASTLOGIN DATETIME
     , CONSTRAINT PK_USER PRIMARY KEY (ID)
);

CREATE TABLE REGISTER (
       ID INT NOT NULL
     , CREATED DATETIME
     , NICK VARCHAR(100)
     , EMAIL VARCHAR(255)
     , PWD VARCHAR(500)
     , CONSTRAINT PK_REGISTER PRIMARY KEY (ID)
);

CREATE TABLE CONTACT (
       ID INT NOT NULL
     , NICK VARCHAR(100) NOT NULL
     , EMAIL VARCHAR(255) NOT NULL
     , NAG INT
     , LASTNAG DATETIME
     , NEXTNAG DATETIME
     , FK_USER_ID INT NOT NULL
     , CONSTRAINT PK_CONTACT PRIMARY KEY (ID)
     , CONSTRAINT FK_CONTACT_1 FOREIGN KEY (FK_USER_ID)
                  REFERENCES USER (ID) ON DELETE CASCADE
);

CREATE TABLE DEBT (
       ID INT NOT NULL
     , DATE DATETIME NOT NULL
     , DESCRIPTION VARCHAR(255)
     , SUM DOUBLE NOT NULL
     , FK_USER_ID INT NOT NULL
     , FK_CONTACT_ID INT NOT NULL
     , CONSTRAINT PK_DEBT PRIMARY KEY (ID)
     , CONSTRAINT FK_DEBT_1 FOREIGN KEY (FK_USER_ID)
                  REFERENCES USER (ID)
     , CONSTRAINT FK_DEBT_2 FOREIGN KEY (FK_CONTACT_ID)
                  REFERENCES CONTACT (ID) ON DELETE CASCADE
);

CREATE TABLE CLAIMED_DEBT (
       ID INT NOT NULL
     , DATE DATETIME NOT NULL
     , DESCRIPTION VARCHAR(255)
     , SUM DOUBLE NOT NULL
     , FK_CONTACT_ID INT NOT NULL
     , FK_USER_ID INT NOT NULL
     , CONSTRAINT PK_CLAIMED_DEBT PRIMARY KEY (ID)
     , CONSTRAINT FK_CLAIMED_DEBT_1 FOREIGN KEY (FK_CONTACT_ID)
                  REFERENCES CONTACT (ID) ON DELETE CASCADE
     , CONSTRAINT FK_CLAIMED_DEBT_2 FOREIGN KEY (FK_USER_ID)
                  REFERENCES USER (ID) ON DELETE CASCADE
);

