CREATE TABLE DEBTNAG.MAILQUEUE (
       ID INT NOT NULL AUTO_INCREMENT
     , CREATED DATETIME
     , RECIPIENT VARCHAR(100)
     , SUBJECT VARCHAR(100)
     , MESSAGE TEXT
     , PRIMARY KEY (ID)
);

